### ISSUE TITLE
Do you have a cuda accelerated version of `bpdndl`?

### ISSUE THREAD

**Issue by CasperN** [bwohlberg/sporco-cuda#2]
Hello, I'm trying out sporco but am having a hard time with the documentation. There really should be better names, they're quite the headache to decode.

I'm trying to do dictionary learning on a few million points of a few hundred dimensions. Is there a GPU accelerated way to do this in your library? Is my best option `bpdndl`?

**Comment by bwohlberg** [comment]
Can you give some examples of the names that are difficult to decode?

If you want to do standard (non-convolutional) dictionary learning, then ``bpdndl`` is your only option at the moment. Have you checked to see whether it really is unacceptably slow with your data set? There isn't a GPU accelerated version yet, but that's on the todo list. If you need it urgently, it should be relatively straightforward to construct a GPU version by replacing NumPy arrays and functions with the corresponding ones from CuPy (see the ``sporco.cupy`` subpackage for examples of the modules for which GPU enabled versions are already available).

**Comment by CasperN** [comment]
Documentation:
A name such as `bpdndl` isn't clear to someone new to the library. While the documentation does expand the acronyms on say https://sporco.readthedocs.io/en/latest/invprob/index.html, they don't always fully expand the acronyms further down. E.g. It would be nice to have the full name of `bpdn` and a link on this page https://sporco.readthedocs.io/en/latest/examples/dl/bpdndl.html#example-dl-bpdndl.
That said, its a pretty minor complaint considering is a young library with good maths. 

Also could you explain how to interpret the verbose output? Or send a link to where these are defined?
`Itn   Fnc       DFid      ℓ1        Cnstr     r_X       s_X       ρ_X       r_D       s_D       ρ_D`


Speed
On 16 cpu, `bdpndl` took about 20 minutes for 15 steps, 3000 points, 128 dimensional vectors. Which suggests it will be very slow for millions of pointso. The program seems to be using just 1 core a lot of the time and only occasionally using 16. I'd like to get your insight on performance and scaling with sporco

**Comment by bwohlberg** [comment]
This issue was moved to bwohlberg/sporco#4

**Comment by bwohlberg** [comment]
I moved this issue to the main sporco repo since the discussion is no longer relevant to the sporco-cuda repo.
