### ISSUE TITLE
Cuda for Robust PCA

### ISSUE THREAD

**Issue by AleBitetto** [bwohlberg/sporco-cuda#5]
Hi,

is it possibile to use Cuda for Robust PCA? Thanks.

P.S. Sorry I wasn't able to label is as "question"

**Comment by bwohlberg** [comment]
The code in this repo only supports a few basic forms of the convolutional sparse coding problem, so the most direct answer would be "no". However, it should be straightforward to modify the ``sporco.admm.rpca`` module in the main SPORCO repo to run on a GPU via CuPy.

**Comment by AleBitetto** [comment]
Thanks for the reply. So is it something that should be added next?

**Comment by bwohlberg** [comment]
I've just pushed an update to the main SPORCO repo that adds CuPy support for the rpca module. A [rough demo script](https://github.com/bwohlberg/sporco-cuda/files/4299174/rpca_video_cupy.py.gz) is attached. Note, though, that CuPy doesn't seem to provide a very large speed improvement for this problem.

I'm closing this issue; if you have any more questions on this, please open an issue in the main SPORCO repo.
