### ISSUE TITLE
error_check.cuh not found

### ISSUE THREAD

**Issue by sray-cwru** [bwohlberg/sporco-cuda#6]
Building wheels for collected packages: sporco-cuda
  Building wheel for sporco-cuda (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z392rldk/sporco-cuda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z392rldk/sporco-cuda/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4ceamery
       cwd: /tmp/pip-install-z392rldk/sporco-cuda/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_ext
  skipping 'sporco_cuda/util.c' Cython extension (up-to-date)
  skipping 'sporco_cuda/cbpdn.c' Cython extension (up-to-date)
  building 'sporco_cuda.util' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/sporco_cuda
  creating build/temp.linux-x86_64-3.6/sporco_cuda/src
  /usr/local/cuda/bin/nvcc -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/cuda/include -Isporco_cuda/src -I/usr/include/python3.6m -c sporco_cuda/src/utils.cu -o build/temp.linux-x86_64-3.6/sporco_cuda/src/utils.o -Xcompiler '-D__builtin_stdarg_start=__builtin_va_start' --compiler-options '-fno-inline' --compiler-options '-fno-strict-aliasing' --compiler-options '-Wall' -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_53,code=sm_53 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_72,code=sm_72 -gencode arch=compute_75,code=sm_75 -Xcompiler '-fPIC'
  sporco_cuda/src/utils.cu:5:27: fatal error: error_check.cuh: No such file or directory
   #include "error_check.cuh"
                             ^
  compilation terminated.
  error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by bwohlberg** [comment]
Thanks for the bug report. This will be fixed shortly.
