### ISSUE TITLE
ImportError when running tests

### ISSUE THREAD

**Issue by mfl22** [bwohlberg/sporco-cuda#9]
I get the `ImportError` when running `python setup.py test`:

`ImportError while importing test module '(...)/sporco-cuda/sporco_cuda/tests/test_cbpdn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sporco_cuda/tests/test_cbpdn.py:7: in <module>
    import sporco_cuda.cbpdn as cucbpdn
sporco_cuda/__init__.py:6: in <module>
    import sporco_cuda.cbpdn
E   ImportError: (...)/sporco-cuda/sporco_cuda/cbpdn.cpython-38-x86_64-linux-gnu.so: undefined symbol: __gxx_personality_v0`

`_______________________________________________________________________________ ERROR collecting sporco_cuda/tests/test_util.py _______________________________________________________________________________`

`ImportError while importing test module '(...)/sparse/sporco-cuda/sporco_cuda/tests/test_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sporco_cuda/tests/test_util.py:4: in <module>
    import sporco_cuda.util as cu
sporco_cuda/__init__.py:6: in <module>
    import sporco_cuda.cbpdn
E   ImportError: (...)/sporco-cuda/sporco_cuda/cbpdn.cpython-38-x86_64-linux-gnu.so: undefined symbol: __gxx_personality_v0`

System specifications: Ubuntu 20.04, CUDA 11.4, ( Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 )

**Comment by bwohlberg** [comment]
Thanks for the bug report. Could you please check your gcc version? It looks as if this error may be a result of [using a version of gcc that's incompatible with your version of nvcc](https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version).

**Comment by mfl22** [comment]
`gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`

I changed `language = 'c'` to `language = 'c++'` in `setup.ext_util` and `setup.ext_cbpdn` and the tests passed now...
